future4code/cruz-marketplace5

src/App.js

atualizacao

---

src/App.js
src/components/AppContainer.js
yarn.lock

instalando npm e yarn

---

src/App.js
src/components/Footer/Footer.js

subindo footer estilizado

---

README.md
public/index.html
src/App.js
src/components/Footer/Footer.js

readme.me link trello. inserindo icon rede social

---

src/App.js
src/components/AppContainer.js

Main dos produtos. Separando produtos do carrossel

---

src/components/Footer/Footer.js

subindo alteracao footer

---

src/App.js
src/components/Header/Header.js

header dentro do components

---

src/App.js
src/components/AppContainer.js
src/components/Footer/Footer.js

arrumando footer

---

src/App.js
src/components/Header/Header.js
src/theme.js

resolvendo conflito

---

src/components/AppContainer.js

subindo os produtos renderizados na Tela pela API

---

src/App.js
src/components/AppContainer.js
src/components/Header/Header.js
src/theme.js

atualizando header

---

src/App.js
src/components/AppContainer.js
yarn.lock

site atualizado

---

src/App.js
src/components/AppContainer.js

filter pesquisar

---

src/components/SellerPage/SellerPage.js

SellerPage funcionando cocorretamente com o API v1.0

---

src/components/AppContainer.js

Feacture produtos- Botoes de filtro

---

src/App.js
src/components/AppContainer.js

subindo botoes

---

src/components/AppContainer.js

comprar ajustado

---

src/App.js
src/components/AppContainer.js

Feacture produtos- filtro de nome do main

---

src/App.js
src/components/AppContainer.js

fitler incompleto

---

src/App.js
src/Parametros.js
src/components/AppContainer.js
src/components/SellerPage/SellerPage.js

filtros finalizados

---

src/App.js
src/components/AppContainer.js
src/components/Cart/Popup.css
src/components/Cart/Popup.js

Carrinho finalizado

---

src/App.js
src/components/AppContainer.js

Feacture produtos- resolvendo conflitos

---

README.md

subindo o readme.Md

---

src/App.js
src/components/AppContainer.js

Integrantes do grupo:
###Elber Ezequiel de Sousa
###Lucas Barros Costa
###Matheus Borges
###Pedro Vitor de Souza
###Gabriel Mina da Silva
###O que funciona
Carrossel
Adicionar o produto no carrinho
filtrar por Valor mínimo e máximo
filtrar por filtrar por Categoria (uma por vez)
filtrar por Título ou descrição
ordenar por Nome
ordenar por Preço
ordenar por Categoria
Campos do produto: Nome ,Descrição ,Preço, Método(s) de pagamento aceito(s) ,Categoria ,Fotos (URLs) ,Número de parcelas
O que não funciona
Tudo funciona
http://unknown-smile.surge.sh/

finalizando para entrega

---

src/App.js
src/components/AppContainer.js
src/components/Cart/Popup.css
src/components/Footer/Footer.js

responsivando TUDO

---

src/App.js
src/components/AppContainer.js
src/components/Cart/Popup.css
src/components/Footer/Footer.js

responsivando 2.0

---

README.md

Feacture produtos
